version: '3.7'

services:  
  rest:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PGRST_DB_URI: postgres://authenticator:authenticator@db:5432/postgres
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_MAX_ROWS: ${PGRST_DB_MAX_ROWS}
      PGRST_JWT_SECRET: ${ACCESS_TOKEN_SECRET}
      PGRST_JWT_AUD: ${AUDIENCE}
      PGRST_OPENAPI_MODE: disabled
    container_name: rest
    networks:
      - stexs
    depends_on:
      - db


  db: 
    image: supabase/postgres:latest
    ports: 
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    container_name: db
    networks:
      - stexs


  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    container_name: mailpit


  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 80:8080
    restart: unless-stopped
    container_name: swagger
    environment:
      SWAGGER_JSON_URL: http://localhost:3001/
    networks:
      - stexs


  minio:
    image: quay.io/minio/minio
    ports: 
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ./docker/minio/data:/data
    container_name: minio
    command: server --console-address ":9001" /data
    networks:
      - stexs
    depends_on:
      - db

    
  postgraphile:
    build: 
      context: .
      dockerfile: ./docker/postgraphile/Dockerfile
    ports: 
      - 5000:5000
    restart: unless-stopped
    container_name: graphile
    command:
      [
        "--plugins",
        "@graphile/pg-pubsub",
        "--append-plugins",
        "/postgraphile/CustomPlugin.js",
        "--connection",
        "postgres://authenticator:authenticator@db:5432/postgres",
        "--port",
        "5000",
        "--cors",
        "--schema",
        "public",
        "--default-role",
        "anon",
        "--jwt-secret",
        "${ACCESS_TOKEN_SECRET}",
        "--jwt-verify-audience",
        "${AUDIENCE}",
        "--subscriptions",
        "--show-error-stack"
      ]
    networks:
      - stexs

  redis:
    image: redis/redis-stack:latest
    ports: 
      - 6379:6379
      - 8001:8001
    container_name: redis
    restart: unless-stopped
    networks:
      - stexs
  
networks:
  stexs:
    driver: bridge
      