version: '3.7'

services:
  auth-api:
    container_name: auth-api
    build: 
      context: .
      dockerfile: ./apps/auth-api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - stexs
  
networks:
  stexs:
    external: true
      