version: '3.8'

services:
  node-app:
    image: node:20.8.0
    working_dir: /auth
    restart: always
    volumes:
      - ./app:/auth/app
      - ./.env:/auth/.env
      - ./env-config.ts:/auth/env-config.ts
      - ./package.json:/auth/package.json
      - ./package-lock.json:/auth/package-lock.json
      - ./tsconfig.json:/auth/tsconfig.json
      - ../../node_modules:/auth/node_modules
      - ./swagger.json:/auth/swagger.json
    command: ["npm", "start"]
    ports:
      - "3001:3001"
    container_name: auth
